import pg from 'pg';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const DATABASE_URL = process.env.DATABASE_URL || 'postgresql://blindtest_user:blindtest_pass@localhost:5432/blindtest';
const OLLAMA_URL = process.env.OLLAMA_URL || 'http://127.0.0.1:11434';
const OLLAMA_MODEL = process.env.OLLAMA_MODEL || 'llama3.2';

const pool = new pg.Pool({ connectionString: DATABASE_URL });

async function getRawGenres() {
  const { rows } = await pool.query(`
    SELECT g.genre, COUNT(*) as count 
    FROM songs_cache, LATERAL jsonb_array_elements_text(ai_genres) AS g(genre) 
    GROUP BY g.genre 
    ORDER BY count DESC;
  `);
  return rows;
}

async function askOllamaToClean(rawGenres) {
  const prompt = `
You are a music genre taxonomy expert.
We have a list of raw music genres and subgenres with their track counts in our game database.
We want to clean, consolidate, and standardise this list into a clean JSON mapping for a multiplayer music guessing game.

Goals:
1. Merge spelling differences (e.g., "bossanova" and "brazilian-bossa-nova" -> "bossa-nova").
2. Standardise regional/language subgenres (e.g., "rap tuga", "portuguese-rap", "rap-tuga" -> "hip-hop-tuga").
3. Group minor subgenres into playable consolidated standard genres (e.g., "emo-rap", "drill", "gangsta-rap" -> "hip-hop-rap").
4. Choose standardised_genre_names in kebab-case format.
5. Create logical groupings (genre_groups) like 'portuguese', 'french', 'spanish', 'brazilian', 'english', 'world'.

Return a JSON object with this exact format:
{
  "mappings": {
    "raw_genre_name": "standardised_genre_name",
    ...
  },
  "genre_groups": [
    {
      "id": "group_name_kebab_case",
      "genreIds": ["standardised_genre_name", ...]
    },
    ...
  ]
}

Here is the raw list of genres and track counts:
${JSON.stringify(rawGenres, null, 2)}
`;

  console.log(`[AI] Querying Ollama (${OLLAMA_MODEL}) to clean genres...`);
  const start = Date.now();
  const res = await fetch(`${OLLAMA_URL}/api/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: OLLAMA_MODEL,
      prompt,
      stream: false,
      format: 'json',
      options: { temperature: 0.1 }
    })
  });

  if (!res.ok) {
    throw new Error(`Ollama returned ${res.status}: ${await res.text()}`);
  }

  const data = await res.json();
  const duration = ((Date.now() - start) / 1000).toFixed(1);
  console.log(`[AI] Ollama finished in ${duration}s.`);
  return JSON.parse(data.response);
}

async function updateDatabase(mappings) {
  console.log(`[DB] Standardising ai_genres in songs_cache...`);
  
  // Get all tracks with their raw genres
  const { rows: tracks } = await pool.query('SELECT id, ai_genres FROM songs_cache WHERE ai_genres IS NOT NULL');
  
  let updated = 0;
  for (const track of tracks) {
    const rawList = Array.isArray(track.ai_genres) ? track.ai_genres : [];
    const cleanSet = new Set();
    
    for (const raw of rawList) {
      const standard = mappings[raw] || mappings[raw.toLowerCase().trim()];
      if (standard) {
        cleanSet.add(standard);
      }
    }
    
    const cleanList = Array.from(cleanSet);
    
    // Update if the genres changed
    if (JSON.stringify(rawList.sort()) !== JSON.stringify(cleanList.sort())) {
      await pool.query(
        'UPDATE songs_cache SET ai_genres = $1::jsonb WHERE id = $2',
        [JSON.stringify(cleanList), track.id]
      );
      updated++;
    }
  }
  
  console.log(`[DB] Successfully updated ${updated} tracks with standardised genres.`);
}

async function main() {
  try {
    const rawGenres = await getRawGenres();
    console.log(`[Start] Found ${rawGenres.length} raw genres in database.`);
    
    if (rawGenres.length === 0) {
      console.log('No genres found to clean. Make sure songs have been processed first.');
      process.exit(0);
    }
    
    const result = await askOllamaToClean(rawGenres);
    
    const outputDir = path.join(__dirname, 'output');
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir);
    }
    
    fs.writeFileSync(
      path.join(outputDir, 'genres-mapping.json'),
      JSON.stringify(result, null, 2)
    );
    console.log(`[File] Saved mapping and groups to scripts/output/genres-mapping.json`);
    
    // Standardise DB
    await updateDatabase(result.mappings);
    
    // Generate Backend configuration code
    const allStandardGenres = [...new Set(Object.values(result.mappings))].sort();
    
    let configCode = `// Standardised Genres generated by AI\n`;
    configCode += `export const GENRES = ${JSON.stringify(allStandardGenres, null, 2)};\n\n`;
    configCode += `export const GENRE_GROUPS = ${JSON.stringify(result.genre_groups, null, 2)};\n`;
    
    fs.writeFileSync(path.join(outputDir, 'genres-config.js'), configCode);
    console.log(`[File] Saved backend configuration to scripts/output/genres-config.js`);
    
  } catch (err) {
    console.error('[Error]', err.message);
  } finally {
    await pool.end();
  }
}

main();
